CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$ 
BEGIN
   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'users_db') THEN
      CREATE DATABASE users_db;
   END IF;
END $$;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS companies (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255) UNIQUE NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
   updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
   deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS users (
   id SERIAL PRIMARY KEY,
   screen_name VARCHAR(255),
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL DEFAULT NULL,
   rank INTEGER DEFAULT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
   updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
   deleted_at TIMESTAMP WITHOUT TIME ZONE
);
