basePath: /
definitions:
  models.User:
    properties:
      companyId:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      rank:
        type: integer
      screenName:
        type: string
      updatedAt:
        type: string
    type: object
  schemas.CreateUserRequest:
    description: This request includes the necessary details to create a new user.
    properties:
      company_id:
        description: |-
          The ID of the company to associate with the new user. This field is optional and must be greater than 0 if provided.
          @Min 0
          @Example 1
        type: integer
      email:
        description: |-
          The email address of the new user. This field is required and must be a valid email address.
          @Format email
          @Example user@example.com
        type: string
      password:
        description: |-
          The password for the new user. This field is required and must contain at least 7 characters.
          @MinLength 7
          @Example 1234567
        minLength: 7
        type: string
      rank:
        description: |-
          The rank of the new user. This field is optional and must be greater than 0 if provided.
          @Min 0
          @Example 1
        type: integer
      screen_name:
        description: |-
          The desired username for the new user. This field is required and must contain at least 4 characters.
          @MinLength 4
          @Example exampleUser
        minLength: 4
        type: string
    required:
    - email
    - password
    - screen_name
    type: object
  schemas.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API server for auth stuff
  title: Auth Service API
  version: v.1.0.0
paths:
  /api/healthcheck:
    get:
      consumes:
      - application/json
      description: Get server status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.HealthCheckResponse'
        "403":
          description: forbidden
          schema:
            type: string
      summary: Show server status
      tags:
      - health
  /api/users:
    post:
      consumes:
      - application/json
      description: Register a new user with email, screen_name, and password
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register new user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
